name = "Fl"
badges = ["travis"]
module_maker="ModuleBuild"
license="artistic_2"
c_source = ['xs']
readme_from="lib/Fl.pod"
abstract_from="lib/Fl.pod"
authors_from="lib/Fl.pod"

[build]
build_class="inc::MBFlExt"

[XSUtil]
needs_compiler_cpp = 1
generate_ppport_h = "xs/include/ppport.h"

[tap_harness_args]
jobs=8
