name = "FLTK"
badges = ["travis"]
module_maker="ModuleBuild"
license="artistic_2"
c_source = ['xs']

[build]
build_class="inc::MBFLTKExt"

[XSUtil]
needs_compiler_cpp = 1
generate_ppport_h = "xs/ppport.h"

[release]
pause_config = "C:/Strawberry/pause.upload"

