name = "FLTK"
badges = ["travis"]
module_maker="ModuleBuildTiny"
license="artistic_2"
requires_external_bin=["sh');\nuse lib 'inc';\nno Module::Build::Tiny;\nuse MBTFLTKBindings;\n('1"]

[release]
pause_config = "C:/Strawberry/pause.upload"
