name = "Fl"
badges = ["travis"]
module_maker="ModuleBuild"
license="artistic_2"
c_source = ['xs']
readme_from="lib/Fl.pod"
markdown_maker = "Pod::Markdown::Github"
abstract_from="lib/Fl.pod"
authors_from="lib/Fl.pod"

[build]
build_class="inc::MBFlExt"

[XSUtil]
needs_compiler_cpp = 1
generate_ppport_h = "xs/include/ppport.h"

[release]
pause_config = "C:/Strawberry/pause.upload"

[tap_harness_args]
jobs=8
